// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	models "Improve/src/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserRoleRepository is an autogenerated mock type for the UserRoleRepository type
type UserRoleRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, role
func (_m *UserRoleRepository) Create(ctx context.Context, role *models.UserRole) error {
	ret := _m.Called(ctx, role)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserRole) error); ok {
		r0 = rf(ctx, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUserRoleRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserRoleRepository creates a new instance of UserRoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserRoleRepository(t mockConstructorTestingTNewUserRoleRepository) *UserRoleRepository {
	mock := &UserRoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
