# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        env:
          MYSQL_ROOT_PASSWORD: "secret"
          MYSQL_USER: "huan"
          MYSQL_PASSWORD: "secret"
          MYSQL_DATABASE: "shop_car"
        ports:
          - 3356:3306
        expose:
          - "3306"
        volumes:
          - database_mysql:/var/lib/mysql
        restart: always
        cap_add:
          - SYS_NICE
        healthcheck:
          test: [ "CMD-SHELL", "echo 'select 1' |mysql -u root -p'secret' --silent" ]
          interval: 30s
          timeout: 20s
          retries: 6
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run migrations
      run: |
        make migrate
 
    - name: Test
      run: make test
