# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

#    services:
#      mysql:
#        image: mysql:latest
#        env:
#          MYSQL_ROOT_PASSWORD: "secret"
#          MYSQL_USER: "huan"
#          MYSQL_PASSWORD: "secret"
#          MYSQL_DATABASE: "shop_car"
#        ports:
#          - 3356:3306
#        volumes:
#          - database_mysql:/var/lib/mysql


    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up MySQL
      uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: '8.0'
        my-cnf: |
          innodb_log_file_size=256MB
          innodb_buffer_pool_size=512MB
          max_allowed_packet=16MB
          max_connections=50
          local_infile=1
        root-password: secret
        user: huan
        password: secret
        database: shop_car
        run: mysql -uroot -h127.0.0.1 -e 'SELECT version()'

    - name: Run migrations
      run: |
        mysql -uroot -h127.0.0.1 -e 'CREATE database shop_car'
        go install github.com/pressly/goose/v3/cmd/goose@latest
        make migrate
 
    - name: Test
      run: make test
